# Generated by Django 5.0.1 on 2025-12-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="intermediaire",
                        max_length=20,
                        verbose_name="Difficulté",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30,
                        help_text="0 pour illimité",
                        verbose_name="Temps limite (minutes)",
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=60, verbose_name="Score de réussite (%)"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True, verbose_name="Mélanger les questions"
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les corrections"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="quizzes",
                        to="courses.document",
                        verbose_name="Documents sources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("qcm", "QCM"),
                            ("vf", "Vrai/Faux"),
                            ("ouvert", "Question ouverte"),
                            ("completion", "Complétion"),
                        ],
                        max_length=20,
                        verbose_name="Type de question",
                    ),
                ),
                ("text", models.TextField(verbose_name="Énoncé")),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des choix pour QCM",
                        verbose_name="Choix de réponses",
                    ),
                ),
                ("correct_answer", models.TextField(verbose_name="Réponse correcte")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explication"),
                ),
                ("points", models.IntegerField(default=1, verbose_name="Points")),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField(verbose_name="Recto (question)")),
                ("back", models.TextField(verbose_name="Verso (réponse)")),
                ("hint", models.TextField(blank=True, verbose_name="Indice")),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("abandoned", "Abandonné"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Score (%)")),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Points gagnés"),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="Points totaux"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="Bonnes réponses"),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="Total questions"),
                ),
                (
                    "time_spent",
                    models.IntegerField(default=0, verbose_name="Temps passé (sec)"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correct"),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Points gagnés"),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.quizattempt",
                        verbose_name="Tentative",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="quizzes.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse utilisateur",
                "verbose_name_plural": "Réponses utilisateurs",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
