# Generated by Django 5.0.1 on 2025-12-08 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du badge"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji ou nom d'icône",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("streak", "Série"),
                            ("completion", "Complétion"),
                            ("mastery", "Maîtrise"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        help_text="Règles d'attribution en JSON",
                        verbose_name="Critères",
                    ),
                ),
                ("points", models.IntegerField(default=10, verbose_name="Points")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Commun"),
                            ("rare", "Rare"),
                            ("epic", "Épique"),
                            ("legendary", "Légendaire"),
                        ],
                        default="common",
                        max_length=20,
                        verbose_name="Rareté",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "gamification_badge",
                "ordering": ["-rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Obtenu le"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=100,
                        help_text="Pourcentage 0-100",
                        verbose_name="Progression",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données contextuelles",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge utilisateur",
                "verbose_name_plural": "Badges utilisateurs",
                "db_table": "gamification_user_badge",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
